id: P004422
initial_creation_type: ocr
created_at: 27/03/2020
last_modified_at: 2021-12-17 11:20:14.841344
source_metadata:
  id: bdr:W2CZ6597
  title: གསུང་འབུམ། གང་ཤར་དབང་པོ
  author: ''
  volumes:
    c982a8db8bee4a4bb685e36029bfba3d:
      image_group_id: I1KG1407
      title: ''
      volume_number: 1
      total_pages: 312
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
